name: Build and Release [Manual]

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.actor == 'DecliningLotus'

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: "0"

      - name: Configure CI Git User
        run: |
          git config --global user.name 'fontsource-bot'
          git config --global user.email 'fontsource-bot@users.noreply.github.com'

      - name: Install packages
        run: yarn

      - name: Query API
        run: yarn parser:gen $GOOGLE_API_KEY
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

      - name: Parse APIv1
        run: yarn parser:v1

      - name: Parse APIv2
        run: yarn parser:v2

      - name: Scrape variable fonts
        run: yarn variable:gen

      - name: Parse variable fonts
        run: yarn variable:parse

      - name: Format files
        run: yarn format:prettier

      - name: Stage changes
        run: git add --all

      - name: Commit files
        run: >-
          git commit -m "chore(build): update API [Manual $GITHUB_RUN_NUMBER]"
        continue-on-error: true

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
